- name: Configuring "{{ microservice_name }}"
  ansible.builtin.debug:
    msg: Building "{{ microservice_name }}" microservice

- name: Import dnf_installation
  ansible.builtin.import_role:
    name: dnf_modules
    tasks_from: main.yml

- name: create user
  ansible.builtin.import_role:
    name: create_user
    tasks_from: main.yml

- name: create directory
  ansible.builtin.import_role:
    name: create_directory
    tasks_from: main.yml

- name: Download and untar
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip
    dest: "{{ directory_path }}"
    remote_src: yes

- name: Execute mvn package
  ansible.builtin.shell: cd "{{ directory_path }}" ; mvn clean package ; mv target/shipping-1.0.jar shipping.jar

- name: Copy shipping systemd service file
  ansible.builtin.template:
    src: shipping.service
    dest: /etc/systemd/system/shipping.service

- name: Execute mvn package
  ansible.builtin.shell: cd "{{ directory_path }}" ; mysql -h "{{ mysql_ip }}" -uroot -p"{{ rb_password }}" < /app/db/"{{ item }}".sql
  loop: "{{ schemas }}"

- name: Systemd start service
  ansible.builtin.import_role:
    name: systemd
    tasks_from: main.yml

