apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName}}
  namespace: {{ include "project" .}}
  labels:
    {{ include "common_values" . | indent 4 }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.appName}}
  template:
    metadata:
      labels:
        app: {{ .Values.appName}}
    spec:
      containers:
        - name: {{ .Values.appName}}-pod
          image: {{ .Values.image}}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.containerPort }}
          env:
          {{- range $key, $value := .Values.env }}
          - name: {{ $key }}
            value: {{ $value }}
          {{- end }}
