apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: roboshop
  labels:
    {{- include "mychart.app" . | nindent 4 }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      {{- if .Values.initContainerEnabled }}
      initContainers:
        {{- range .Values.init_cont_user_create }}
        - name: {{ .init_name }}
          image: {{ .image }}
          env:
            - name: SCHEMA_FILE
              value: {{ .schema_file }}
            {{- range $key, $value := .initenv }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
        {{- end }}
      {{- end }}

      containers:
        - name: {{ .Values.appName }}
          image: {{ .Values.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.containerPort }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-service
  namespace: roboshop
  labels:
    app: {{ .Values.appName }}
spec:
  selector:
    app: {{ .Values.appName }}
  ports:
    - protocol: TCP
      port: {{ .Values.target_port }}
      targetPort: {{ .Values.service_port }}
  type: {{ .Values.service_type }}
