- name: Configuring "{{ microservice_name }}"
  ansible.builtin.debug:
    msg: Building "{{ microservice_name }}" microservice

- name: Import dnf_installation
  ansible.builtin.import_role:
    name: dnf_modules
    tasks_from: main.yml

- name: Import systemd installation
  ansible.builtin.import_role:
    name: systemd
    tasks_from: main.yml

- name: Execute mysql_secure_installation command
  ansible.builtin.shell: mysql_secure_installation --set-root-pass "{{ roboshop_password }}"