- name: Import dnf_installation
  ansible.builtin.import_role:
    name: dnf_modules
    tasks_from: main.yml

- name: Create User
  ansible.builtin.import_role:
    name: create_user
    tasks_from: main.yml

- name: Create Directory
  ansible.builtin.import_role:
    name: create_directory
    tasks_from: main.yml

- name: Untar the zipfile
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
    dest: "{{  directory_path }}"
    remote_src: yes

- name: NPM Install
  ansible.builtin.shell: npm install
  args:
    chdir: "{{ directory_path }}"

- name: Copy user service file
  ansible.builtin.template:
    src: user.service
    dest: /etc/systemd/system/user.service

- name: systemd start user service
  ansible.builtin.import_role:
    name: systemd
    tasks_from: main.yml