- name: Import monodb repo_copy role
  ansible.builtin.import_role:
    name: repo_copy
    tasks_from: main.yml

- name: Import dnf_modules role
  ansible.builtin.import_role:
    name: dnf_modules
    tasks_from: main.yml

- name: Replace 127.0.0.1 to 0.0.0.0 in /etc/mongod.conf
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Import systemd and mongod nginx
  ansible.builtin.import_role:
    name: systemd
    tasks_from: main.yml