#- name: Configuring "{{ microservice_name }}"
#  ansible.builtin.debug:
#    msg: Building "{{ microservice_name }}" microservice
#
#- name: Import create_user
#  ansible.builtin.import_role:
#    name: create_user
#    tasks_from: main.yml
#
#- name: Copy Repo
#  ansible.builtin.import_role:
#    name: repo_copy
#    tasks_from: main.yml
#
#- name: copy catalogue.service
#  ansible.builtin.template:
#    src: catalogue.service
#    dest: /etc/systemd/system/catalogue.service
#    owner: "{{ dir_owner }}"
#    mode: '0744'
#
#- name: Import create_directory
#  ansible.builtin.import_role:
#    name: create_directory
#    tasks_from: main.yml
#
#- name: Extract Roboshop package
#  ansible.builtin.unarchive:
#    src: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
#    dest: "{{ directory_path }}"
#    remote_src: yes
#
#- name: Import dnf_installation
#  ansible.builtin.import_role:
#    name: dnf_modules
#    tasks_from: main.yml
#
#- name: NPM Install
#  ansible.builtin.shell: cd /"{{ directory_path }}" ; npm install
#
#- name: systemd start application
#  ansible.builtin.import_role:
#    name: systemd
#    tasks_from: main.yml
#
#- name: mongo load data
#  ansible.builtin.shell: mongosh --host {{ mongo_ip }} </app/db/master-data.js

#===================
#  Docker Setup
#====================
- name: Import dnf and install nginx
  ansible.builtin.import_role:
    name: dnf_modules
    tasks_from: main.yml

- name: create catalogue container
  containers.podman.podman_container:
    name: catalogue
    image: public.ecr.aws/w8x4g9h7/roboshop-v3/catalogue
    state: started
    ports:
      - "8080:8080"
    env:
      MONGO: true
      MONGO_URL: "mongodb://mongodb.manojpadigineti.cloud:27017/catalogue"

- name: create schema-load container
  containers.podman.podman_container:
    name: schema-load
    image: public.ecr.aws/w8x4g9h7/roboshop-v3/schema-load
    state: started
    env:
      DB_TYPE: "mongo"
      APP_GIT_URL: "https://github.com/roboshop-devops-project-v3/catalogue"
      DB_HOST: "mongodb.manojpadigineti.cloud"
      SCHEMA_FILE: "db/master-data.js"